name: Build locally
  on: pull_request
env:
  PUSH_IMAGE: false
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - uses: buildpacks/github-actions/setup-pack@v5.9.5
      - uses: buildpacks/github-actions/setup-tools@v5.9.5
      - id: create-stack
        run: |
          ./scripts/create-and-push-stack.sh
